runtime: nodejs16

handlers:
  - url: /assets
    static_dir: dist/assets
  - url: /img
    static_dir: dist/img
  - url: /(.*\..+)$
    static_files: dist/\1
    upload: dist/(.*\..+)$
  - url: /(.*)
    secure: always
    static_files: dist/index.html
    upload: dist/index.html
